var num1 = 2039;
var num2 = -4.983;
var num3 = 22223;
var num4 = -0.12;
var hi = 'Hi!';
var bye = 'Bye!';
var whut = 'Whut?';
var yup = true;
var nope = false;
var empty;
console.log("The very first number--the one you shouldn't tell anyone--is " + num1);
console.log("The second number--the one you can tell you mom if you want--is " + num2);
console.log("The third number is " + num3);
console.log("Finally, the fourth number, chosen entirely at random, is " + num4);
console.log("As for the strings, the first might be used in greeting: " + hi);
console.log("The second is more appropriate for parting: " + bye);
console.log("Finally, when one is confused, one might say: " + whut);
console.log("To thine own self be " + yup);
console.log("And it must follow as the night the day, thou can'st not be " + nope + " to any man.");
console.log("Also, if you try to call an empty variable, it will evaluate to " + empty + ".");
